version: '3.7'

services:

  db:
    image: postgres:latest
    container_name: "postgres_glass"
    restart: 'always'
    environment:
      - "POSTGRES_PASSWORD=asdaHnj@43KLm2K02"
      - "POSTGRES_USER=glass_star_db"
      - "POSTGRES_DB=glass_star_db"
    ports:
      - 5432:5432
    volumes:
      - type: 'bind'
        source: './dbdata'
        target: '/var/lib/postgresql/data'