# Generated by Django 4.0.5 on 2022-06-21 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Done'), ('F', 'Failed')], default='P', max_length=250, verbose_name='order status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modification time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='order user')),
            ],
            options={
                'verbose_name': 'user order',
                'verbose_name_plural': 'user orders',
            },
        ),
        migrations.CreateModel(
            name='DoneOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
