# Generated by Django 4.0.5 on 2022-06-21 16:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('items', django.db.models.manager.Manager()),
            ],
        ),
    ]
