# Generated by Django 4.0.5 on 2022-06-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quentity',
            field=models.IntegerField(null=True),
        ),
    ]
